version: '2'
services: 
  df-server:
    build:
      context: ./
      dockerfile: Dockerfile-node
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment: 
      - DATABASE_HOST=db
    volumes: 
      - ./src:/app/src/
  db:
    build:
      context: ./
      dockerfile: Dockerfile-mysql
