# From the official Mysql image
FROM mysql

# Set root mysql password
ENV MYSQL_ROOT_PASSWORD datafiniti

# Set (and create) mysql database
ENV MYSQL_DATABASE datafiniti
ENV MYSQL_USER datafiniti
ENV MYSQL_PASSWORD datafiniti
